name: youtube_explode_dart CI

on:
  push:
    branches: [ master, main ]
    paths:
      - 'packages/youtube_explode_dart/**'
      - '.github/workflows/youtube_explode_dart-ci.yml'
  pull_request:
    branches: [ master, main ]
    paths:
      - 'packages/youtube_explode_dart/**'
  workflow_dispatch: {}

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/youtube_explode_dart

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Install dependencies
        run: dart pub get

      - name: Clean only .freezed.dart files
        run: find lib -name "*.freezed.dart" | xargs rm -f

      - name: Generate code (freezed / json_serializable)
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Analyze project source
        run: dart analyze --fatal-infos

      - name: Run tests
        run: dart test
